add_lunch_combo chroma_emulator-eng
add_lunch_combo chroma_grouper-user
add_lunch_combo chroma_hammerhead-user
add_lunch_combo chroma_mako-user
add_lunch_combo chroma_shamu-user
add_lunch_combo chroma_tilapia-user
